namespace: ci-operator
name: template
version: 0.0.1
readme: README.md
authors:
  - josiah@redhat.com
description: Openshift template processor
issues: https://github.com/ci-operator/template/issues
repository:
  https://github.com/ci-operator/template.git
build_ignore: 
  - build
  - install
  - '*.tar.gz'
  - '*~'
